spring.application.name=fleetmanagement

spring.datasource.url=jdbc:mysql://localhost:3306/fleetmanagement_db
spring.datasource.username=root
spring.datasource.password=qrpasses321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8080